services:
  medisync-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medisync-corba-client
    volumes:
      - ./generated:/app/generated
    env_file:
      - .env